#if !canImport(ObjectiveC)
import XCTest

extension TemporaryFileTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TemporaryFileTests = [
        ("test_inMemoryFile_collection", test_inMemoryFile_collection),
        ("test_inMemoryFile_mutableCollection", test_inMemoryFile_mutableCollection),
        ("test_inMemoryFile_mutableDataProtocol", test_inMemoryFile_mutableDataProtocol),
        ("test_inMemoryFile_rangeReplaceableCollection", test_inMemoryFile_rangeReplaceableCollection),
        ("test_inMemoryFile_sequence", test_inMemoryFile_sequence),
        ("test_inMemoryFile", test_inMemoryFile),
        ("test_process", test_process),
        ("test_temporaryDirectory", test_temporaryDirectory),
        ("test_temporaryFile_closure", test_temporaryFile_closure),
        ("test_temporaryFile_copy", test_temporaryFile_copy),
        ("test_temporaryFile_truncate", test_temporaryFile_truncate),
        ("test_temporaryFile", test_temporaryFile),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(TemporaryFileTests.__allTests__TemporaryFileTests),
    ]
}
#endif
